[project]
name = "overlay-manager"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pywin32>=310",
    "qrcode>=8.2",
]
