name: Test & release overlays

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test overlays
    runs-on: windows-latest
    env:
      PYTHONPATH: ${{ github.workspace }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Set up just
        uses: extractions/setup-just@v2
      - name: Set up uv
        uses: astral-sh/setup-uv@v1
        with:
          version: "latest"
      - name: Install dependencies
        run: uv sync --extra dev
      - name: lint
        run: uv run ruff check .
      - name: format
        run: uv run ruff format --check
      - name: Run tests
        run: uv run pytest -v

  release:
    name: Release overlays
    runs-on: windows-latest
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Concatenate source files
        run: |
          Get-Content main.py, helpers.py | Set-Content overlays.py
        shell: pwsh
      - name: Commit and push overlays.py
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add overlays.py
          git commit -m "Add generated overlays.py"
          git push
        shell: pwsh
